//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Bmc.rc
//
#define IDR_RT_MANIFEST1                1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_FORMVIEW                    101
#define IDR_MAINFRAME                   128
#define IDR_BmcTYPE                     129
#define IDD_DIALOG_FILTEREDIMAGE        133
#define IDD_DIALOG_IMAGE                134
#define IDD_RESULT_IMAGE                135
#define IDD_VIEWFORM_CONTROL2           136
#define IDC_BUTTON1                     1000
#define IDC_NORMAL_MC_RAY_TRACING       1000
#define IDC_BUTTON_ADDCAMERA            1000
#define IDC_EDIT1                       1001
#define IDC_LIGHT_SCALE                 1001
#define IDC_BUTTON_CLEARALL             1001
#define IDC_EDIT2                       1002
#define IDC_SUNLIGHT_SCALE              1002
#define IDC_BUTTON_RVMCAMERA            1002
#define IDC_EDIT3                       1003
#define IDC_SKYLIGHT_SCALE              1003
#define IDC_EDIT_FRAMENUMBER            1003
#define IDC_CHECK1                      1004
#define IDC_SUNLIGHT_CK                 1004
#define IDC_CHECK_C2_DIRECT_LIGHTING    1004
#define IDC_CHECK2                      1005
#define IDC_SKYLIGHT_CK                 1005
#define IDC_CHECK_C2_INDIRECT_LIGHTING  1005
#define IDC_SPIN1                       1006
#define IDC_LIGHT_SOURCE_SCALE_SPIN     1006
#define IDC_CHECK_C2_CAUSTIC_EFFECT     1006
#define IDC_SPIN2                       1007
#define IDC_SUNLIGHT_SCALE_SPIN         1007
#define IDC_CHECK_C2_MIRROR_EFFECT      1007
#define IDC_SPIN3                       1008
#define IDC_SKYLIGHT_SCALE_SPIN         1008
#define IDC_CHECK_DIRECTIONAL_LIGHTING  1008
#define IDC_CHECK_C2_DIRECTIONAL_LIGHTING 1008
#define IDC_SPIN4                       1009
#define IDC_PHOTON_NUMBER_SPIN          1009
#define IDC_CHECK_C2_TOTALLY_PHOTONMAP  1009
#define IDC_SPIN5                       1010
#define IDC_RAY_NUMBER_SPIN             1010
#define IDC_SPIN6                       1011
#define IDC_SHADOW_RAY_NUMBER_SPIN      1011
#define IDC_POINT_RD                    1012
#define IDC_WIRE_RD                     1013
#define IDC_SOLID_RD                    1014
#define IDC_RADIO1                      1015
#define IDC_IMAGE_WIDTH_SPIN            1016
#define IDC_PHOTON_NUMBER               1017
#define IDC_RAY_NUMBER                  1018
#define IDC_IMAGE_HEIGHT                1019
#define IDC_IMAGE_WIDTH                 1020
#define IDC_IMAGE_HEIGHT_SPIN           1021
#define IDC_SUNLIGHT_COLOR              1022
#define IDC_LIGHT_TEST_RAY_NUMBER       1023
#define IDC_SKYLIGHT_COLOR              1024
#define IDC_BMC_RAY_TRACING             1025
#define IDC_RAY_NUMBER2                 1026
#define IDC_INTENSITY_SCALE             1026
#define IDC_THREAD_NUMBER               1027
#define IDC_IRRADIANCE_CACHE_TOLERANCE  1028
#define IDC_IRRADIANCE_CACHE_CK         1029
#define IDC_GRADIENT_IRRADIANCE_CACHE_CK 1030
#define IDC_SHOW_RAY_TRACING_RESULT     1031
#define IDC_CHECK3                      1032
#define IDC_BMC_INTEGRATION_CB          1032
#define IDC_CHECK_MOTION_BLUR           1032
#define IDC_GROUPBOX_FILTER             1033
#define IDC_CHECK_APPLYFILTER           1034
#define IDC_CHECK_PIXEL                 1035
#define IDC_EDIT_PIXEL                  1036
#define IDC_CHECK_PERCEPTION            1037
#define IDC_EDIT_PERCEPTION             1038
#define IDC_CHECK_NORMAL                1039
#define IDC_EDIT_NORMAL                 1040
#define IDC_CHECK_DEPTH                 1041
#define IDC_EDIT_DEPTH                  1042
#define IDC_CHECK_MATERIAL              1043
#define IDC_EDIT_MATERIAL               1044
#define IDC_BUTTON_STARTFILTER          1045
#define IDC_BUTTON_SHOW_FILTER          1046
#define IDC_EDIT_FILTERBOXSIZE          1047
#define IDC_STATIC_FILTERBOXSIZE        1048
#define IDC_BUTTON_SAVE                 1049
#define IDC_BUTTON_LOAD                 1050
#define IDC__VIDEO_RENDER               1050
#define IDC_LIST_CAMERALIST             1051
#define IDC_BUTTON_CAMPREVIEW           1052
#define IDC_RADIO_SINGLE                1053
#define IDC__VIDEO_RENDER2              1053
#define IDC_RADIO3                      1054
#define IDC_RADIO_VIDEO                 1054
#define IDC_EDIT_RESULTPATH             1055
#define IDC_BUTTON_SELECTPATH           1056
#define IDC_PROGRESS_VIDEORENDER        1057
#define IDC_BUTTON_SAVEPATH             1058
#define IDC_BUTTON_LOADPATH             1059
#define IDC_EDIT_COLORFILENAME          1060
#define IDC_EDIT_GEOFILENAME            1061
#define IDC_BUTTON_VIDEO_FILTER_COL     1062
#define IDC_BUTTON_VIDEOFILTER_GEO      1063
#define IDC_EDIT_OUTPUTDIR              1064
#define IDC_EDIT6                       1065
#define IDC_EDIT_FILTER_FRAME_NUM       1065
#define IDC_BUTTON_VIDEOFILTER_OUTPUT   1066
#define IDC_EDIT5                       1069
#define IDC_EDIT5_THREAD_NUM            1069
#define IDC_BUTTON_STOP_VIDEOFILTER     1070
#define IDC_CHECK_RESAMPLE              1071
#define IDC_EDIT_SAMPLE_THRESHOLD       1072
#define IDC_EDIT4                       1073
#define IDC_EDIT_RENDER_END             1073
#define IDC_EDIT_RENDER_FROM            1074
#define IDC_CHECK_OUT_WEIGHTS           1076
#define IDC_CHECK6                      1077
#define IDC_EDIT_IRRADIANCECACHE_PATH   1078
#define IDC_BUTTON_IRR_PATH             1079
#define IDC_RADIO2                      1080
#define IDC_RADIO_COLOR_TRIANGLE        1080
#define ID_CONFIG_SAVE                  32771
#define ID_CONFIG_LOAD                  32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
